# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 23:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20160121_2141'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Goods',
        ),
        migrations.AlterModelTable(
            name='goods',
            table='goods',
        ),
    ]
