# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20160122_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dummy',
            field=models.TextField(default=2),
        ),
    ]
