# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 23:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20160122_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(verbose_name=b'Created At')),
            ],
        ),
    ]
